# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  app.topic.chat:
        class: AppBundle\Topic\ChatTopic
        arguments: ['@doctrine.orm.default_entity_manager']
        tags:
            - { name: gos_web_socket.topic }
